"""Initial schema setup

Revision ID: 704a77c49f7c
Revises: 
Create Date: 2026-08-23 09:54:11.122817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '704a77c49f7c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('estimated_waste_kg', sa.Float(), nullable=False),
    sa.Column('waste_type', sa.Enum('PET', 'HDPE', 'LDPE', 'PP', 'OTHER_RECYCLABLE_PLASTIC', 'MIXED_PLASTIC', name='wastetype'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='prioritylevel'), nullable=False),
    sa.Column('last_collection_date', sa.DateTime(), nullable=True),
    sa.Column('overflow_status', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_points_id'), 'collection_points', ['id'], unique=False)
    op.create_table('depots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_depots_id'), 'depots', ['id'], unique=False)
    op.create_table('optimization_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('number_of_vehicles', sa.Integer(), nullable=False),
    sa.Column('number_of_collection_points', sa.Integer(), nullable=False),
    sa.Column('total_distance_before', sa.Float(), nullable=True),
    sa.Column('total_distance_after', sa.Float(), nullable=True),
    sa.Column('total_duration_before', sa.Float(), nullable=True),
    sa.Column('total_duration_after', sa.Float(), nullable=True),
    sa.Column('waste_collected', sa.Float(), nullable=False),
    sa.Column('distance_saved_percentage', sa.Float(), nullable=True),
    sa.Column('time_saved_percentage', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'PARTIAL_SUCCESS', 'FAILED', 'INFEASIBLE', name='optimizationstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_runs_id'), 'optimization_runs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DRIVER', 'MANAGER', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ON_ROUTE', 'OFF_DUTY', 'INACTIVE', name='driverstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('waste_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_point_id', sa.Integer(), nullable=False),
    sa.Column('estimated_quantity_kg', sa.Float(), nullable=False),
    sa.Column('actual_quantity_kg', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['collection_point_id'], ['collection_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waste_records_id'), 'waste_records', ['id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=50), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('capacity_kg', sa.Float(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'ON_ROUTE', 'OFF_DUTY', 'INACTIVE', name='vehiclestatus'), nullable=False),
    sa.Column('current_latitude', sa.Float(), nullable=True),
    sa.Column('current_longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_vehicle_number'), 'vehicles', ['vehicle_number'], unique=True)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_date', sa.Date(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('total_distance_km', sa.Float(), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Float(), nullable=False),
    sa.Column('total_waste_kg', sa.Float(), nullable=False),
    sa.Column('utilization_percentage', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'ASSIGNED', 'STARTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='routestatus'), nullable=False),
    sa.Column('optimization_run_id', sa.Integer(), nullable=True),
    sa.Column('geometry_geojson', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_table('route_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('collection_point_id', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('estimated_arrival_time', sa.DateTime(), nullable=True),
    sa.Column('actual_arrival_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ARRIVED', 'COLLECTED', 'SKIPPED', 'FAILED', name='stopstatus'), nullable=False),
    sa.ForeignKeyConstraint(['collection_point_id'], ['collection_points.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_stops_id'), 'route_stops', ['id'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_stop_id', sa.Integer(), nullable=False),
    sa.Column('expected_quantity_kg', sa.Float(), nullable=False),
    sa.Column('actual_quantity_kg', sa.Float(), nullable=False),
    sa.Column('collection_time', sa.DateTime(), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('proof_image_url', sa.String(length=255), nullable=True),
    sa.Column('failure_reason', sa.Enum('NO_WASTE', 'LOCATION_INACCESSIBLE', 'VEHICLE_ISSUE', 'COLLECTION_POINT_CLOSED', 'EXCESSIVE_WASTE', 'OTHER', name='failurereason'), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['route_stop_id'], ['route_stops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_stop_id')
    )
    op.create_index(op.f('ix_collections_id'), 'collections', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collections_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_route_stops_id'), table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_vehicles_vehicle_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_waste_records_id'), table_name='waste_records')
    op.drop_table('waste_records')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_optimization_runs_id'), table_name='optimization_runs')
    op.drop_table('optimization_runs')
    op.drop_index(op.f('ix_depots_id'), table_name='depots')
    op.drop_table('depots')
    op.drop_index(op.f('ix_collection_points_id'), table_name='collection_points')
    op.drop_table('collection_points')
    # ### end Alembic commands ###
